<?php

namespace Nvidia\WeChat\BackendBundle\Repository;

/**
 * WeChatEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeChatEventRepository extends \Doctrine\ORM\EntityRepository
{
}
