<?php

namespace AppBundle\Repository;

/**
 * VisitShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitShareRepository extends \Doctrine\ORM\EntityRepository
{
    public function findShares()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT vs FROM AppBundle:VisitShare vs WHERE vs.toShare IS NOT NULL ORDER BY vs.id DESC'
            )
            ->setMaxResults(10)
            ->getResult();
    }

    public function findReads($shareId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT vs FROM AppBundle:VisitShare vs WHERE vs.fromShare=:shareId  ORDER BY vs.id DESC'
            )
            ->setParameters(array('shareId' => $shareId))
            ->setMaxResults(10)
            ->getResult();
    }
}
